// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteArrays.proto

package com.bizosys.hsearch.byteutils;

public final class ByteArrays {
  private ByteArrays() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ArrayDouble extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayDouble.newBuilder() to construct.
    private ArrayDouble() {
      initFields();
    }
    private ArrayDouble(boolean noInit) {}
    
    private static final ArrayDouble defaultInstance;
    public static ArrayDouble getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayDouble getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_fieldAccessorTable;
    }
    
    // repeated double val = 1 [packed = true];
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Double> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public double getVal(int index) {
      return val_.get(index);
    }
    private int valMemoizedSerializedSize = -1;
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(valMemoizedSerializedSize);
      }
      for (double element : getValList()) {
        output.writeDoubleNoTag(element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getValList().size();
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Double>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 9: {
              addVal(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated double val = 1 [packed = true];
      public java.util.List<java.lang.Double> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public double getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, double value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(double value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Double>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Double> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Double>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayDouble)
    }
    
    static {
      defaultInstance = new ArrayDouble(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayDouble)
  }
  
  public static final class ArrayFloat extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayFloat.newBuilder() to construct.
    private ArrayFloat() {
      initFields();
    }
    private ArrayFloat(boolean noInit) {}
    
    private static final ArrayFloat defaultInstance;
    public static ArrayFloat getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayFloat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_fieldAccessorTable;
    }
    
    // repeated float val = 1 [packed = true];
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public float getVal(int index) {
      return val_.get(index);
    }
    private int valMemoizedSerializedSize = -1;
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(valMemoizedSerializedSize);
      }
      for (float element : getValList()) {
        output.writeFloatNoTag(element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getValList().size();
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 13: {
              addVal(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated float val = 1 [packed = true];
      public java.util.List<java.lang.Float> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public float getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, float value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(float value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayFloat)
    }
    
    static {
      defaultInstance = new ArrayFloat(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayFloat)
  }
  
  public static final class ArrayInt extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayInt.newBuilder() to construct.
    private ArrayInt() {
      initFields();
    }
    private ArrayInt(boolean noInit) {}
    
    private static final ArrayInt defaultInstance;
    public static ArrayInt getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayInt getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayInt_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayInt_fieldAccessorTable;
    }
    
    // repeated int32 val = 1 [packed = true];
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public int getVal(int index) {
      return val_.get(index);
    }
    private int valMemoizedSerializedSize = -1;
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(valMemoizedSerializedSize);
      }
      for (int element : getValList()) {
        output.writeInt32NoTag(element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addVal(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int32 val = 1 [packed = true];
      public java.util.List<java.lang.Integer> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public int getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, int value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(int value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayInt)
    }
    
    static {
      defaultInstance = new ArrayInt(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayInt)
  }
  
  public static final class ArrayLong extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayLong.newBuilder() to construct.
    private ArrayLong() {
      initFields();
    }
    private ArrayLong(boolean noInit) {}
    
    private static final ArrayLong defaultInstance;
    public static ArrayLong getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayLong getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayLong_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayLong_fieldAccessorTable;
    }
    
    // repeated int64 val = 1 [packed = true];
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Long> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public long getVal(int index) {
      return val_.get(index);
    }
    private int valMemoizedSerializedSize = -1;
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(valMemoizedSerializedSize);
      }
      for (long element : getValList()) {
        output.writeInt64NoTag(element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (long element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Long>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addVal(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int64 val = 1 [packed = true];
      public java.util.List<java.lang.Long> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public long getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, long value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(long value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Long>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Long> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Long>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayLong)
    }
    
    static {
      defaultInstance = new ArrayLong(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayLong)
  }
  
  public static final class ArrayBool extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayBool.newBuilder() to construct.
    private ArrayBool() {
      initFields();
    }
    private ArrayBool(boolean noInit) {}
    
    private static final ArrayBool defaultInstance;
    public static ArrayBool getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayBool getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayBool_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayBool_fieldAccessorTable;
    }
    
    // repeated bool val = 1 [packed = true];
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Boolean> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Boolean> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public boolean getVal(int index) {
      return val_.get(index);
    }
    private int valMemoizedSerializedSize = -1;
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(valMemoizedSerializedSize);
      }
      for (boolean element : getValList()) {
        output.writeBoolNoTag(element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 1 * getValList().size();
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Boolean>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addVal(input.readBool());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated bool val = 1 [packed = true];
      public java.util.List<java.lang.Boolean> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public boolean getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, boolean value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(boolean value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Boolean>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Boolean>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayBool)
    }
    
    static {
      defaultInstance = new ArrayBool(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayBool)
  }
  
  public static final class ArrayString extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayString.newBuilder() to construct.
    private ArrayString() {
      initFields();
    }
    private ArrayString(boolean noInit) {}
    
    private static final ArrayString defaultInstance;
    public static ArrayString getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayString getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayString_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayString_fieldAccessorTable;
    }
    
    // repeated string val = 1;
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<java.lang.String> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public java.lang.String getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (java.lang.String element : getValList()) {
        output.writeString(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (java.lang.String element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayString prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayString result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayString.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayString();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayString internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayString();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayString.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayString getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayString.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayString build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayString buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayString buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayString returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayString) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayString other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayString.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.String>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              addVal(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated string val = 1;
      public java.util.List<java.lang.String> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public java.lang.String getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.val_.set(index, value);
        return this;
      }
      public Builder addVal(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.String>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayString)
    }
    
    static {
      defaultInstance = new ArrayString(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayString)
  }
  
  public static final class ArrayBytes extends
      com.google.protobuf.GeneratedMessage {
    // Use ArrayBytes.newBuilder() to construct.
    private ArrayBytes() {
      initFields();
    }
    private ArrayBytes(boolean noInit) {}
    
    private static final ArrayBytes defaultInstance;
    public static ArrayBytes getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArrayBytes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.ByteArrays.internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_fieldAccessorTable;
    }
    
    // repeated bytes val = 1;
    public static final int VAL_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> val_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public com.google.protobuf.ByteString getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.google.protobuf.ByteString element : getValList()) {
        output.writeBytes(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes result;
      
      // Construct using com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes) {
          return mergeFrom((com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes other) {
        if (other == com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes.getDefaultInstance()) return this;
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              addVal(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // repeated bytes val = 1;
      public java.util.List<com.google.protobuf.ByteString> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public com.google.protobuf.ByteString getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.val_.set(index, value);
        return this;
      }
      public Builder addVal(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.ArrayBytes)
    }
    
    static {
      defaultInstance = new ArrayBytes(true);
      com.bizosys.hsearch.byteutils.ByteArrays.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.ArrayBytes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayInt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayInt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayLong_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayLong_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayBool_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayBool_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayString_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayString_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020byteArrays.proto\022\035com.bizosys.hsearch." +
      "byteutils\"\036\n\013ArrayDouble\022\017\n\003val\030\001 \003(\001B\002\020" +
      "\001\"\035\n\nArrayFloat\022\017\n\003val\030\001 \003(\002B\002\020\001\"\033\n\010Arra" +
      "yInt\022\017\n\003val\030\001 \003(\005B\002\020\001\"\034\n\tArrayLong\022\017\n\003va" +
      "l\030\001 \003(\003B\002\020\001\"\034\n\tArrayBool\022\017\n\003val\030\001 \003(\010B\002\020" +
      "\001\"\032\n\013ArrayString\022\013\n\003val\030\001 \003(\t\"\031\n\nArrayBy" +
      "tes\022\013\n\003val\030\001 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayDouble_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayDouble.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayFloat_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayFloat.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_ArrayInt_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_bizosys_hsearch_byteutils_ArrayInt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayInt_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayInt.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_ArrayLong_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_bizosys_hsearch_byteutils_ArrayLong_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayLong_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayLong.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_ArrayBool_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_bizosys_hsearch_byteutils_ArrayBool_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayBool_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayBool.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_ArrayString_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_bizosys_hsearch_byteutils_ArrayString_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayString_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayString.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayString.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_ArrayBytes_descriptor,
              new java.lang.String[] { "Val", },
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes.class,
              com.bizosys.hsearch.byteutils.ByteArrays.ArrayBytes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
