// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiHash.proto

package com.bizosys.hsearch.byteutils;

public final class MultiHash {
  private MultiHash() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class MultiHashDouble extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashDouble.newBuilder() to construct.
    private MultiHashDouble() {
      initFields();
    }
    private MultiHashDouble(boolean noInit) {}
    
    private static final MultiHashDouble defaultInstance;
    public static MultiHashDouble getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashDouble getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // repeated double val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Double> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public double getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      for (double element : getValList()) {
        output.writeDouble(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      {
        int dataSize = 0;
        dataSize = 8 * getValList().size();
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Double>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 17: {
              addVal(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated double val = 2;
      public java.util.List<java.lang.Double> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public double getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, double value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(double value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Double>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Double> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Double>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashDouble)
    }
    
    static {
      defaultInstance = new MultiHashDouble(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashDouble)
  }
  
  public static final class MultiHashFloat extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashFloat.newBuilder() to construct.
    private MultiHashFloat() {
      initFields();
    }
    private MultiHashFloat(boolean noInit) {}
    
    private static final MultiHashFloat defaultInstance;
    public static MultiHashFloat getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashFloat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // repeated float val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public float getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      for (float element : getValList()) {
        output.writeFloat(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      {
        int dataSize = 0;
        dataSize = 4 * getValList().size();
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 21: {
              addVal(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated float val = 2;
      public java.util.List<java.lang.Float> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public float getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, float value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(float value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashFloat)
    }
    
    static {
      defaultInstance = new MultiHashFloat(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashFloat)
  }
  
  public static final class MultiHashInt extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashInt.newBuilder() to construct.
    private MultiHashInt() {
      initFields();
    }
    private MultiHashInt(boolean noInit) {}
    
    private static final MultiHashInt defaultInstance;
    public static MultiHashInt getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashInt getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // repeated int32 val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public int getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      for (int element : getValList()) {
        output.writeInt32(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      {
        int dataSize = 0;
        for (int element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 16: {
              addVal(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated int32 val = 2;
      public java.util.List<java.lang.Integer> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public int getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, int value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(int value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashInt)
    }
    
    static {
      defaultInstance = new MultiHashInt(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashInt)
  }
  
  public static final class MultiHashLong extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashLong.newBuilder() to construct.
    private MultiHashLong() {
      initFields();
    }
    private MultiHashLong(boolean noInit) {}
    
    private static final MultiHashLong defaultInstance;
    public static MultiHashLong getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashLong getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // repeated int64 val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Long> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public long getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      for (long element : getValList()) {
        output.writeInt64(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      {
        int dataSize = 0;
        for (long element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Long>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 16: {
              addVal(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated int64 val = 2;
      public java.util.List<java.lang.Long> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public long getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, long value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(long value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Long>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Long> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Long>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashLong)
    }
    
    static {
      defaultInstance = new MultiHashLong(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashLong)
  }
  
  public static final class MultiHashBool extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashBool.newBuilder() to construct.
    private MultiHashBool() {
      initFields();
    }
    private MultiHashBool(boolean noInit) {}
    
    private static final MultiHashBool defaultInstance;
    public static MultiHashBool getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashBool getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // repeated bool val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Boolean> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Boolean> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public boolean getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      for (boolean element : getValList()) {
        output.writeBool(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      {
        int dataSize = 0;
        dataSize = 1 * getValList().size();
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.Boolean>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 16: {
              addVal(input.readBool());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated bool val = 2;
      public java.util.List<java.lang.Boolean> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public boolean getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, boolean value) {
        result.val_.set(index, value);
        return this;
      }
      public Builder addVal(boolean value) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Boolean>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.Boolean>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashBool)
    }
    
    static {
      defaultInstance = new MultiHashBool(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashBool)
  }
  
  public static final class MultiHashString extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashString.newBuilder() to construct.
    private MultiHashString() {
      initFields();
    }
    private MultiHashString(boolean noInit) {}
    
    private static final MultiHashString defaultInstance;
    public static MultiHashString getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashString getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashString_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashString_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // repeated string val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> val_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getValList() {
      return val_;
    }
    public int getValCount() { return val_.size(); }
    public java.lang.String getVal(int index) {
      return val_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      for (java.lang.String element : getValList()) {
        output.writeString(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getValList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashString prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashString result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashString.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashString();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashString internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashString();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashString.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashString getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashString.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashString build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashString buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashString buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.val_ != java.util.Collections.EMPTY_LIST) {
          result.val_ =
            java.util.Collections.unmodifiableList(result.val_);
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashString returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashString) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashString other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashString.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.val_.isEmpty()) {
          if (result.val_.isEmpty()) {
            result.val_ = new java.util.ArrayList<java.lang.String>();
          }
          result.val_.addAll(other.val_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 18: {
              addVal(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // repeated string val = 2;
      public java.util.List<java.lang.String> getValList() {
        return java.util.Collections.unmodifiableList(result.val_);
      }
      public int getValCount() {
        return result.getValCount();
      }
      public java.lang.String getVal(int index) {
        return result.getVal(index);
      }
      public Builder setVal(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.val_.set(index, value);
        return this;
      }
      public Builder addVal(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.String>();
        }
        result.val_.add(value);
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.val_.isEmpty()) {
          result.val_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.val_);
        return this;
      }
      public Builder clearVal() {
        result.val_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashString)
    }
    
    static {
      defaultInstance = new MultiHashString(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashString)
  }
  
  public static final class MultiHashBytes extends
      com.google.protobuf.GeneratedMessage {
    // Use MultiHashBytes.newBuilder() to construct.
    private MultiHashBytes() {
      initFields();
    }
    private MultiHashBytes(boolean noInit) {}
    
    private static final MultiHashBytes defaultInstance;
    public static MultiHashBytes getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiHashBytes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.byteutils.MultiHash.internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_fieldAccessorTable;
    }
    
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // required bytes val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private boolean hasVal;
    private com.google.protobuf.ByteString val_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasVal() { return hasVal; }
    public com.google.protobuf.ByteString getVal() { return val_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasVal) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      if (hasVal()) {
        output.writeBytes(2, getVal());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      if (hasVal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVal());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes result;
      
      // Construct using com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes();
        return builder;
      }
      
      protected com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes.getDescriptor();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes getDefaultInstanceForType() {
        return com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes) {
          return mergeFrom((com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes other) {
        if (other == com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 18: {
              setVal(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // required bytes val = 2;
      public boolean hasVal() {
        return result.hasVal();
      }
      public com.google.protobuf.ByteString getVal() {
        return result.getVal();
      }
      public Builder setVal(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVal = true;
        result.val_ = value;
        return this;
      }
      public Builder clearVal() {
        result.hasVal = false;
        result.val_ = getDefaultInstance().getVal();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.byteutils.MultiHashBytes)
    }
    
    static {
      defaultInstance = new MultiHashBytes(true);
      com.bizosys.hsearch.byteutils.MultiHash.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.byteutils.MultiHashBytes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashString_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashString_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017multiHash.proto\022\035com.bizosys.hsearch.b" +
      "yteutils\"+\n\017MultiHashDouble\022\013\n\003key\030\001 \002(\014" +
      "\022\013\n\003val\030\002 \003(\001\"*\n\016MultiHashFloat\022\013\n\003key\030\001" +
      " \002(\014\022\013\n\003val\030\002 \003(\002\"(\n\014MultiHashInt\022\013\n\003key" +
      "\030\001 \002(\014\022\013\n\003val\030\002 \003(\005\")\n\rMultiHashLong\022\013\n\003" +
      "key\030\001 \002(\014\022\013\n\003val\030\002 \003(\003\")\n\rMultiHashBool\022" +
      "\013\n\003key\030\001 \002(\014\022\013\n\003val\030\002 \003(\010\"+\n\017MultiHashSt" +
      "ring\022\013\n\003key\030\001 \002(\014\022\013\n\003val\030\002 \003(\t\"*\n\016MultiH" +
      "ashBytes\022\013\n\003key\030\001 \002(\014\022\013\n\003val\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashDouble_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashDouble.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashFloat_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashFloat.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashInt_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashInt.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashLong_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashLong.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashBool_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashBool.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashString_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashString_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashString_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashString.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashString.Builder.class);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_byteutils_MultiHashBytes_descriptor,
              new java.lang.String[] { "Key", "Val", },
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes.class,
              com.bizosys.hsearch.byteutils.MultiHash.MultiHashBytes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
